version: '3.4'
services:

    redis:
        image: redis:5.0.5
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - production
        volumes:
            - ${HUMBLE_DATA}/redis:/var/lib/redis
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        restart: always

networks:
    production: